# Generated by Django 3.0.8 on 2020-08-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20200802_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginModel',
        ),
        migrations.DeleteModel(
            name='mlModel',
        ),
    ]
