# Generated by Django 3.0.8 on 2020-08-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_loginmodel_mlmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginModel',
        ),
        migrations.DeleteModel(
            name='mlModel',
        ),
    ]
