# Generated by Django 3.0.8 on 2020-08-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_auto_20200805_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='key_table',
            fields=[
                ('mymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loginapp.MyModel')),
                ('key', models.IntegerField()),
            ],
            bases=('loginapp.mymodel',),
        ),
    ]
